../hdl/PC.sv
../hdl/Add4.sv
../hdl/add_immediate.sv
../hdl/Mux2.sv
../hdl/InstructionMemory.sv
../hdl/RegisterFile.sv
../hdl/ImmediateGenerator.sv
../hdl/BranchCondition.sv
../hdl/Controller.sv
../hdl/ALU.sv
../hdl/DataMemory.sv
../hdl/WriteBack.sv
../hdl/Processor.sv
../verif/reference_model/structs.sv
../verif/reference_model/defines.sv 
../verif/reference_model/ref_model.sv 
../verif/reference_model/bind_ref_model.sv
