../hdl/Add4.sv
../hdl/add_immediate.sv
../hdl/ALU.sv
../hdl/BranchCondition.sv
../hdl/Controller.sv
../hdl/DataMemory.sv
../hdl/ImmediateGenerator.sv
../hdl/InstructionMemory.sv
../hdl/Mux2.sv
../hdl/PC.sv
../hdl/RegisterFile.sv
../hdl/WriteBack.sv
../hdl/cache_subsystem_L1.sv
../hdl/cache_subsystem_L2.sv
../hdl/Processor.sv
../hdl/bus_controller.sv
../hdl/top.sv
../verif/reference_model/structs.sv
../verif/reference_model/defines.sv 
../verif/reference_model_top/properties_for_assumes.sv 
../verif/reference_model_top/ref_model_top.sv 
../verif/reference_model_top/bind_ref_model_top.sv
